### ISSUE TITLE
Error when performing queries containing relations to several other resources

### ISSUE THREAD

**Issue by martinheitmann** [sureshHARDIYA/intromat-fhir#32]
When performing a query that includes a relation to two or more FHIR resources for a single field: 

```
query Observation {
    Observation(_id: "5e7a08d9dd081a3c58102642") {
        id
        status
        subject {
            ... on Patient {
                id
                active
            }
            ... on Location {
                id
                name
            }
        }
    }
}
```

The server throws an error: 

```
{
    "errors": [
        {
            "path": [
                "Observation",
                "subject"
            ],
            "message": "Abstract type Observationsubject_subject_Union must resolve to an Object type at runtime for field Observation.subject with value [], received \"undefined\". Either the Observationsubject_subject_Union type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.",
            "locations": [
                {
                    "line": 5,
                    "column": 9
                }
            ],
            "extensions": {
                "resource": {
                    "resourceType": "OperationOutcome",
                    "issue": [
                        {
                            "severity": "error",
                            "code": "exception",
                            "diagnostics": "Abstract type Observationsubject_subject_Union must resolve to an Object type at runtime for field Observation.subject with value [], received \"undefined\". Either the Observationsubject_subject_Union type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function."
                        }
                    ]
                }
            }
        }
    ],
    "data": {
        "Observation": {
            "id": "5e7a08d9dd081a3c58102642",
            "status": "final",
            "subject": null
        }
    }
}
```
Here, it has been manually confirmed that at least one patient exists, and the patient has been set in the query:

```
mutation ObservationCreate {
    ObservationCreate(resource: {

  resourceType: Observation,
  status: "final",
  subject: "5e7a082cdd081a3c5810263c",
  category: [
    {
      coding: [
        {
          system: "http://terminology.hl7.org/CodeSystem/observation-category",
          code: "vital-signs",
          display: "Vital Signs"
        }
      ]
    }
  ],
  code: {
    coding: [
      {
        system: "http://loinc.org",
        code: "29463-7",
        display: "Body Weight"
      },
      {
        system: "http://loinc.org",
        code: "3141-9",
        display: "Body weight Measured"
      },
      {
        system: "http://snomed.info/sct",
        code: "27113001",
        display: "Body weight"
      },
      {
        system: "http://acme.org/devices/clinical-codes",
        code: "body-weight",
        display: "Body Weight"
      }
    ]
  },
  effectiveDateTime: "2016-03-28",
  valueQuantity: {
    value: 185,
    unit: "lbs",
    system: "http://unitsofmeasure.org",
    code: "[lb_av]"
  }
}
) {
    id
    resourceType
}
}
```
How can we make these kinds of queries work?

**Comment by sureshHARDIYA** [comment]
@martinheitmann  I was checking for this issue. It seems when `Observation` resource was created it was not tested. Whenever you create any resource, it would have been much better if it was thoroughly tested. 

I was running the code and found several issues. For example, there are fields that were declared for no reason.  

Anyway, in your query you posted above, you are trying to query the `virtual field`. It should be resolved before you can query on it. I ended up spending the entire day to find the issue and fixing it :D. 

I found the problem but the solution requires a bit of work. And explaining the problem here would be an essay, so I will leave it until I can fix the issue. But the good thing about this ISSUE was I was able to find one of the huge drawbacks of HL7 FHIR Schema. I think you can recognize it too. 

```
mutation ObservationCreate {
    ObservationCreate(resource: {

  resourceType: Observation,
  status: "final",
  subject: "5e7a082cdd081a3c5810263c",
 ....
```

When you create the Observation, here `subject` could be `Patient`, or `Location`, or `Device`. 

How will the backend know if that is a patient or location or device?  One way to find out is to search the entire database until we find the object ID which is overkill. This needs to be addressed and somehow this is also a solution to this problem. 

I was able to fix it assuming `subject` is `patient` but we need a more solid way. I will give a fresh start tomorrow and see if I can find a solution. 

Regards
// SKM

**Comment by hunghkit** [comment]
btw, @martinheitmann  when you want to add patient as subject on Observation create, you should use patient instead of subject in input

**Comment by martinheitmann** [comment]
Thanks for the response, @sureshHARDIYA, and sorry that it took so long. I agree that we should have considered this when we tested the resources in the first place. As far as I remember, we didn't consider that since it depended on having other resources implemented and working before testing out the relationships.

At the time I don't think we had a good solution to this either, and probably ended up forgetting about it. While I think we're starting to get the general idea, our knowlegde regarding both the HL7 FHIR schema and querying relationships in GraphQL is still somewhat limited. 

I understand the general issue, and I'm really thankful that you fixed it in that particular case. We're still facing the same problem with the other resources, though. There may be some resources where we don't need to perform relational queries on certain fields, so if this is limited to only a few resources a temporary workaround will probably do. I'll discuss it with the others as soon as I can.

@hunghkit Noted. Thanks for letting me know. 

Sorry for the inconvenience. 

- Martin H
