### ISSUE TITLE
Creating resources with predefined ID

### ISSUE THREAD

**Issue by Kolbein** [sureshHARDIYA/intromat-fhir#35]
Is it possible to create resources in MongoDB with ID given by the queries? After clarifying with Sam how the resources should be mapped using 'uuid' from each Muzima model, these should be mapped to FHIR-side resources' id. _id seems to be defined as Element type. @sureshHARDIYA

**Comment by sureshHARDIYA** [comment]
@Kolbein  I am not sure if I understand. You need to explain with an example.

**Comment by Kolbein** [comment]
As of now, when you create resources in the database they automatically get an ID. Is it possible to insert an ID in the GraphQL mutation when creating a resource in the database to give the resource that ID. In that case you can get the resource using that ID in the getPatientById query.

The reason we want this is that the Muzima resources we're mapping contain a 'uuid' field which should be mapped to 'id' on the FHIR side of things. 

mutation PatientCreate {
  PatientCreate(resource: {
      resourceType: Patient
      id: "7357"
  }
) {
  id 
  }
}

https://wiki.openmrs.org/display/projects/Patient+Resource

**Comment by sureshHARDIYA** [comment]
Hi, it should be possible. But, for that, you need to change the model and when you create the Patient,  you have to check if the request contains ID. Then you have to create the patient. There is no built-in method based on what I can understand.

**Comment by martinheitmann** [comment]
Please let me know if there's a better way to solve this. I tried to dig my way down to where I can check for an id in the request, and found that I can extract it in the resolver if it's available as an argument:

`module.exports.createPatient = function createPatient(
	root,
	args,
	context = {},
	info,
) {
	return new Promise(async (resolve, reject) => {
		try {
			const { server: { model }, version, req, res } = context;
			//console.log(args);
			if(args.id) args.resource._id = args.id
			const patient = await model.patients.createData(args.resource);
			resolve(patient)
		} catch (e) {
			reject(e);
		}
	});
};`

From there I declare _id as a part of the Schema(and also add it to permitFields) :
`const Schema = new mongoose.Schema(
		Object.assign(domainResource, {
			_id: String,
			resourceType: {
				type: String,
				required: true,
				enum: ['Patient'],
			},
                        ...
		}),
	);`

Running this query:
`mutation PatientCreate {
  PatientCreate(
      id: "test-id-1234",
      resource: {
          resourceType: Patient
          name: [
            {
              use: "official",
              family: "Chalmers",
              given: [
                "Peter",
                "James"
              ]
            },
            {
              use: "usual",
              given: [
                "Jim"
              ]
            },
            {
              use: "maiden",
              family: "Windsor",
              given: [
                "Peter",
                "James"
              ],
              period: {
                end: "2002"
              }
            }
          ]
          gender: "male"
        contact: [
        {
    
          name: {
            text: "mr. F. de Hond"
          },
          telecom: [
            {
              system: "phone",
              value: "022-655 7654"
            },
            {
              system: "email",
              value: "KNO@burgersumc.nl"
            },
            {
              system: "fax",
              value: "022-655 0998"
            }
          ],
          address: {
            line: [
              "West Wing, floor 5"
            ]
          }
        }
      ]
          telecom: [
          {
            use: "home"
          },
          {
            system: "phone",
            value: "(03) 5555 6473",
            use: "work",
            rank: "1"
          },
          {
            system: "phone",
            value: "(03) 3410 5613",
            use: "mobile",
            rank: "2"
          },
          {
            system: "phone",
            value: "(03) 5555 8834",
            use: "old",
            period: {
              end: "2014"
            }
          }
        ]
        active: true
          address: [
            {
              type: "postal"
              line: ["3300 Washtenaw Avenue, Suite 227"]
              city: "Ann Arbor"
              state: "MI"
              postalCode: "48104"
              country: "USA"
            }
          ],
        identifier: [
          {
            use: "usual",
            type: {
              coding: [
                {
                  system: "http://terminology.hl7.org/CodeSystem/v2-0203",
                  code: "MR"
                }
              ]
            },
            system: "urn:oid:1.2.36.146.595.217.0.1",
            value: "12345",
            period: {
              start: "2001-05-06"
            },
            assigner: {
              display: "Acme Healthcare"
            }
          }
        ],
    }
  ) {
    id
    resourceType
    name { family }
    address {
      id
      line
      type
    }
    identifier {
      use,
      assigner {
        display
      }
    }
    identifier {
      use,
      assigner {
        display
      }
    }
  }
}`

The server returns:
`{
    "data": {
        "PatientCreate": {
            "id": "test-id-1234",
            "resourceType": "Patient",
            "name": [
                {
                    "family": "Chalmers"
                },
                {
                    "family": null
                },
                {
                    "family": "Windsor"
                }
            ],
            "address": [
                {
                    "id": "5e838a0a24846263b0b2bcb4",
                    "line": [
                        "3300 Washtenaw Avenue, Suite 227"
                    ],
                    "type": "postal"
                }
            ],
            "identifier": [
                {
                    "use": "usual",
                    "assigner": {
                        "display": "Acme Healthcare"
                    }
                }
            ]
        }
    }
}`

Is there a better way to do this? This will have to be implemented in every resource for it to work.

**Comment by sureshHARDIYA** [comment]
@Kolbein  @martinheitmann  In `HL7 FHIR` it is possible to create `identifier` yourself. So, passing `id: "test-id-1234",` like this okay. 

I am not sure about your intention but storing ID like that is fine. However, you can not force MongoDB to create `(_id)`. I recommend save it as a different field and map it later.

**Comment by martinheitmann** [comment]
If I haven't misunderstood, querying a resource by other fields than its _id isn't supported, right? That was the main intention behind setting the id of the resource, so that we can easily query earch resource by their id.

For example, this isn't supported...
```
query Patient {
    Patient(id: "test-id-1234-5678"){
         id
    resourceType
    name { family }
```

I'm able to set the id field of the resource, but I can't query on it. Can we fix that somehow?

**Comment by sureshHARDIYA** [comment]
Each resource can be queried by ID. 

```
query Patient {
    Patient(_id: "5dcc0734d39e0045d82b6eae") {
        id
        name { family }
    }
}
```
There is nothing you have to do to support this. If you are querying like above and you are getting error, then there is something wrong in the code.

**Comment by martinheitmann** [comment]
That works, yes. But if we can't override the internal MongoDB _id value, we'll have to be able to query by something else instead.

So say that we decide to query each resource by a `uuid` instead (which we can implement as an extension or whatever), how could we do that?

The reason why I'd like to do this is so that when we receive e.g. a patient from the mUzima app that already has an id, we can just assign that id somewhere in the resource and query it using that field.

**Comment by sureshHARDIYA** [comment]
What you can query with is defined in the query.

https://github.com/sureshHARDIYA/intromat-fhir/blob/26b38798a86ca786e6d097cd12ec9565a823f1a9/src/resources/4_0_0/profiles/patient/query.js#L34

It is NOT defined that you have to query by `_id`.  So, instead of `_id`, you should be able to query by any field. To debug I would:

1. Use `uuid` field in query and log https://github.com/sureshHARDIYA/intromat-fhir/blob/master/src/resources/4_0_0/profiles/patient/resolver.js#L15 `args` and see if args correctly recognizes the `uuid` field or not. 
2. If `uuid` is recognized, then it goes to the model. https://github.com/sureshHARDIYA/intromat-fhir/blob/master/src/models/patient.js#L148 HERE. Try to log here and see `params`. 

3. Then check line https://github.com/sureshHARDIYA/intromat-fhir/blob/master/src/models/patient.js#L151. Here it is using `findOne`.  The function `findOne` can take the object as input like:

```
Patient.findOne({ age: 21, location: "New York" }, function(err, result) {
  if (err) {
    res.send(err);
  } else {
    res.send(result);
  }
});
```
I don't have a working example in my computer so, I can not tell you exactly where is the issue. But based on the description, it should be possible to query using any field. If you pass `uuid` and GraphQL says, you can not query by `uuid` that means, the schema does not allow to query by `uuid`. In that case, you have allow to query by `uuid` in the schema.  

If you have a hosted resource server with GRAPHIQL enabled, pass me the link and I can try to check what type of error it returns.

**Comment by Kolbein** [comment]
When trying to create a patient in the resource server providing a uuid with Martin's proposed id solution as commented above, I am successfully able to do so with the following query: 
![patient success](https://user-images.githubusercontent.com/32332560/80115105-a0500f00-8584-11ea-8d31-6a1f0edaeac3.PNG)


If I don't provide an id, this is the error I get:
![patient error](https://user-images.githubusercontent.com/32332560/80115102-9fb77880-8584-11ea-9f14-bd7b189456e2.PNG)

**Comment by sureshHARDIYA** [comment]
Closing thread, due to inactive feedbacks.
